// ignore_for_file: file_names

const Map<String, String> en_US = {
  '扫码换电': 'Scan to Swap',
  "换电": "Battery Swapping / Swapee",
  "商城": "Swapee Shop",
  "购买代步": "Get your Bike",
  "钱包余额": "Wallet Balance",
  "十秒换电": "10s Swapee",
  "个人中心": "Personal Profile",
  "钱包余额（元）": "Wallet",
  "本月换电（次）": "Swapee done/month",
  "当前套餐剩余（次）": "Balance/times",
  "商城订单": "Orders Placed",
  "待付款": "To Pay",
  "待发货": "To Ship",
  "待收货": "To Receive",
  "全部订单": "All Orders",
  "常用功能": "Frequently Used",
  "我的车辆": "My Bikes",
  "服务网点": "Service Outlets",
  "客服中心": "Customer Service",
  "设置": "Settings",
  "公告信息": "Information ",
  "更多": "More",
  "管理员": "Admin",
  "温馨提示": "Gentle Reminder",
  "暂不能使用换电服务，请先绑定车辆":
      "Swapee service is temporarily not available, please register your bike",
  "无车，去购买": "Purchase my bike now",
  "有车，去绑定": "Register my bike now",
  "库存": "Stock",
  "台": "Unit",
  "元": "Dollar",
  "配送方式": "Mode of Delivery",
  "快递免邮": "Free Shipping",
  "保障": "Assurance",
  "假一赔四，付款后48小时内发货，坏单包赔":
      "Delivery 1-3 Working Days Upon Payment. Defect-Free Coverage",
  "参数": "Specification",
  "品牌": "Brand",
  "配置": "Configuration",
  "商品详情": "Product Details",
  "联系客服": "Contact Support",
  "我想要": "Wishlist",
  "请选择规格分类": "Please select a category",
  "购买数量": "Purchase Quantity",
  "确认购买": "Confirm Purchase",
  "暂无收货地址": "No shipping address yet",
  "去设置": "Go to Settings",
  "商品信息": "Product Information",
  "订单备注": "Order Message",
  "选填": "Option",
  "合计": "Total",
  "提交订单": "Submit Order",
  "支付订单": "Order Payment",
  "购买商品": "Purchase Product",
  "选择支付方式": "Select Payment Type",
  "确认支付": "Confirm Payment",
  "订单支付成功": "Payment Successful",
  "关于我们": "About Us",
  "用户协议": "User Agreement",
  "充值协议": "Top-Up Agreement",
  "交货政策": "Delivery Policy",
  "隐私政策": "Privacy Policy",
  "官方网站": "Official Website",
  "联系电话": "Contact Number",
  "电子邮箱": "Email",
  "车架号": "Chassis Number",
  "路管局锁头编码": "LTA Tag Number",
  "车牌号": "Registration Plate No",
  "电池SN码": "Battery Serial Number",
  "电池型号": "Battery Model",
  "电压/容量": "Voltage/Capacity",
  "绑定日期": "Registration Date",
  "公告消息": "Notification",
  "查看全文": "Show All",
  "修改手机号": "Change Mobile No",
  "修改昵称": "Change Nickname",
  "收货地址": "Delivery Address",
  "多语言": "More Language",
  "退出登录": "Logout",
  "当前手机号": "Current Mobile No",
  "请输入新手机号": "Current Mobile No",
  "请输入验证码": "Please enter OTP",
  "请稍后": "Please wait",
  "确定": "Confirm",
  "请输入1~40个字符": "Please enter 1-40 characters",
  "完成": "Complete",
  "修改、添加": "Change or Add",
  "新增收货地址": "Additional Delivery Address",
  "我的二维码": "My QR Code",
  "请向线下服务人员出示个人二维码，以便店员扫码为你解绑电池":
      "Please show your QR Code to our staff to unbind/deregister the battery",
  "钱包": "Wallet",
  "余额": "Balance",
  "充值余额不可提现": "Top-Up Credits are not eligible for withdrawal",
  "消费明细": "Spending Details",
  "去充值": "Top-Up",
  "余额充值": "Top-Up Balance",
  "选择充值金额": "Select Top-Up Amount",
  "当前余额": "Current Balance",
  "我已认真阅读并同意《充值协议》":
      "I have read and agreed to the《Top-Up Agreement》of this app",
  "一经充值，不支持退款、提现，请合理选择充值金额":
      "Please select correct top-up amount. Top-Ups are non-refundable and non-withdrawable",
  "立即充值": "Top-Up Now",
  "导航": "Directions",
  "该电柜暂不能提供服务，请前往其他电柜换电":
      "This kiosk is temporarily unavailable, please proceed to other kiosk for Swapee",
  "可换电": "Can Swapee",
  "准备": "Preparing",
  "登录": "Login",
  "登录/注册": "Login/Register",
  "欢迎使用": "Welcome to use",
  "请输入手机号": "Please enter mobile no",
  "请输入密码": "Please enter password",
  "注册账号": "Register Account",
  "忘记密码": "Forgot Password",
  "请输入6位验证码": "Please enter 6-digit OTP",
  "获取验证码": "Request OTP",
  "下一步": "Next",
  "已有账号，立即登录": "Account exist, login now",
  "新加坡": "Singapore",
  "中国大陆": "Mainland China",
  "基础保障": "Basic Guarantee",
  "假一赔四": "假一赔四",
  "正品保障，假一赔四": "Genuine Product Guarantee",
  "付款后48小时内发货": "Delivery 1-3 Working Days Upon Payment",
  "商品自付款完成起，48小时内发货": "商品自付款完成起，48小时内发货",
  "坏单包赔": "Defect-Free Coverage",
  "所售商品在签收时如有商品破损、变质、动植物死亡等情况，可在24小时内向我们举证，我们将在48小时内处理":
      "Any defects and damages ocurred shall be reported within 24hrs upon delivery. We seek to resolve the issue within the next 48hrs",
  "我知道了": "Got It",
  "型号": "Model",
  "颜色分类": "Colour Type",
  "车架材质": "Chassis/Frame Material",
  "载重量": "Load Capacity",
  "最高时速": "Top Speed",
  "纯电续航": "Pure battery range",
  "电池类型": "Battery Type",
  "电池容量": "Battery Capacity",
  "整车重量": "Bike Weight",
  "商品参数": "Product Specification",
  "你可在“个人中心-商城订单”中查看订单详情":
      "You can check your order details in 'Personal Profile>Bazaar Orders'",
  "返回首页": "Return to Main Page",
  "确认绑定": "Confirm Registration",
  "完善账号信息": "Full Account Information",
  "绑定车辆": 'Register bike',
  "请录入车辆编码": "Please enter bike serial",
  "绑定成功": "Registration is successful",
  "查看我的车辆": "View my bikes",
  "暂无空仓，请前往其他电柜或稍后再试":
      "No slots available at the moment, please proceed to other kiosks or try again later",
  "查看附近电柜": "View nearest kiosk",
  "稍后再试": "Try again later",
  "暂无可用电池，请前往其他电柜或稍后再试":
      "Swapee is unavailable at the moment, please proceed to other kiosks or try again later",
  "该电柜区已停电暂不能提供服务，请前往其他电柜换电":
      "Kiosks in this zone are experiencing power outage, please proceed to other kiosks to continue Swapee",
  "对准电柜屏幕二维码": "Align with kiosk QR Code",
  "输入电柜ID": "Enter Kiosk ID",
  "打开手电筒": "Turn on the flashlight",
  "电柜ID": "Kiosk ID",
  "切换扫码": "Switch to Scan",
  "历史记录": "Record History",
  "换电须知": "Swapee Instructions",
  "下次不再提示": "Do not remind again",
  "若已购买套餐，系统将自动扣除有效套餐内的换电次数以抵扣换电费用":
      "If you have purchased a bundle, the system will automatically deduct the number of Swapees from the valid bundle instead of the standard Swapee fees",
  "单次换电": "Single Swapee",
  "购买换电套餐更实惠": "Purchase a Swapee bundle for better value",
  "提示：开始换电后，将会打开空仓，请保持安全距离":
      "Tip: When you start Swapee, maintain a safe distance from the opening slot door",
  "可换电(颗)": "Available for Swapee (Pcs)",
  "当前换电套餐": "Current Swapee Bundles",
  "剩余4次": "4 Swapees left",
  "有效期": "Effective Date",
  "开始换电": "Start Swapee",
  "换电指引": "Swapee Guide",
  "第1步": "Step 1",
  "空仓打开，放入待充电池后关闭仓门":
      "Slot is open, insert depleted battery and close the door",
  "第2步": "Step 2",
  "等待电池安全检测": "Please hold while we conduct battery safety checks",
  "第3步": "Step 3",
  "仓门打开，取出可用电池后关闭仓门":
      "Slot is open, take out the charged battery and close the door",
  "好的，开始换电": "Okay, start Swapee!",
  "服务进行中": "Service in progress",
  "换电信息": "Swapee Information",
  "换电进行中": "Swapee in progress",
  "订单信息": "Order Information",
  "放入仓": "Insert into slot",
  "取出仓": "Retrieve from slot",
  "如有疑问，请联系客服": "Please contact support if in doubt",
  "换电时间": "Swapee Time",
  "放入电池SN码": "Insert Battery Serial No",
  "取出电池SN码": "Retrieve Battery Serial No",
  "计费规则": "Billing Plan",
  "对订单有疑问": "I have questions with order",
  "服务终止": "Service Terminated",
  "因仓门打开失败，换电终止": "Door failed to open, Swapee terminated",
  "如需帮助，请联系客服": "Please contact support if assistance is needed",
  "拨打客服电话": "Call Swapee Support Hotline",
  "因操作超时，换电终止": "Exceeded operation timing, Swapee terminated",
  "未检测到电池，换电终止": "Battery is not detected, Swapee terminated",
  "若你的电池还在仓内， 可在其他用户换电前重开仓门":
      "If your battery is still in slot, you may retrieve your battery before the next user start Swapee",
  "因电池SN码不匹配，已被电柜吞并，换电终止":
      "Battery serial no. does not match our records. Battery has been withheld by the kiosk, Swapee terminated",
  "正为你临时保管电池，请在3分钟内取出被吞电池":
      "The battery is being temporarily stored for you, please retrieve withheld battery within 3 minutes",
  "取吞并电池": "Retrieve withheld battery",
  "订单详情": "Order Details",
  "交易成功": "Success",
  "共1件商品": "1 product in total",
  "确认收货": "Goods Received",
  "已发货": "Item Shipped",
  "支付成功": "Payment Successful",
  "下单成功": "Successfully Ordered",
  "支付交易号": "Payment Transaction No",
  "剩余付款时间": "Payment Time Left",
  "取消订单": "Cancel Order",
  "去支付": "Proceed to pay",
  "取消订单说明": "Cancellation Instructions",
  "确认提交": "Confirm Submission",
  "订单取消成功": "Cancellation Successful",
  "交易关闭": "Close Transaction ",
  "操作成功": "Operation Successful",
  "再次购买": "Purchase again",
  "分期付款": "Installment",
  "线下支付": "Offline Payment",
  "如需分期付款，请点击以上图标链接": "For installment, please click above",
  "让我们相关客服人员为你服务": "Let our customer service officer serve you",
  "使用记录": "Usage Record",
  "换电中": "Swapee in action",
  "消费金额": "Amount Spent",
  "查看详情": "Check Details",
  "换电记录详情": "Swapee Detailed Records",
  "电柜名称": "Kiosk Name",
  "换电结果": "Swapee Result",
  "电池剩余电量": "Battery Power Left",
  "车辆服务": "Bike Service",
  "电池服务": "Battery Service",
  "工作日": "Working Day",
  "联系": "Contact",
  "意见反馈": "Opinions & Feedbacks",
  "催建电柜": "Request for Kiosk",
  "Hi~,你是遇到以下问题吗？": "Hi, are you experiencing the following issues?",
  "常见问题": "FAQs",
  "工作时间": "Working Hours",
  "换一批": "Batch Change",
  "请选择": "Please Select",
  "充换电柜地址征集": "Swapee Kiosk Directory",
  "你最需要充换电柜安置在哪？告诉我们": "Where do you need the Swapee kiosk to be? Tell Us",
  "建议地址": "Suggested address",
  "您还需要我们为您解决什么问题": "Any other issues to resolve for you?",
  "提交": "Submit",
  "公告详情": "Announcement Details",
  "确认要退出帐号吗": "Confirm Logout?",
  "点错了": "Wrong",
  "收货人": "Addressee",
  "所在地区": "Location",
  "详细地址": "Full Address",
  "请填写收货人姓名": "Addressee Last Name/Surname",
  "请填写收货人手机号": "Addressee Mobile No.",
  "省市区县、乡镇等": "Building No. Street Name",
  "街道、楼牌号等": "Unit No.",
  "保存": "Save",
  "删除": "Delete",
  "是否要确认删除该地址": "Do you want to confirm deletion of this address",
  "删除成功": "Deleted",
  "编辑收货地址": "Edit shipping address",
  "我的套餐": "My Bundle",
  "未生效": "Not active",
  "购买更多套餐": "Purchase more bundle",
  "套餐换电更划算": "Swapee bundle is more cost-effective",
  "查看更多": "View more",
  "套餐说明": "Swapee Bundle Instructions",
  "暂无使用记录": "No usage record at the moment",
  "去购买": "Proceed to buy",
  "全部": "All",
  "暂无交易记录": "No transaction record at the moment",
  "去绑定": "Proceed to register",
  "暂未绑定车辆": "No registered bikes at the moment",
  "暂无服务网点": "No service outlets at the moment",
  "暂无消息": "No message at the moment",
  "网络加载失败": "Internet connection failed",
  "重置密码": "Reset password",
  "验证码错误或已过期": "OTP is wrong or has expired",
  "请再次输入密码": "Please re-enter password",
  "重置密码成功": "Password successfully reset",
  "充值": "Top-Up",
  "消费": "Consumption",
  "换电扣费": "Swapee Deductions",
  "购买套餐": "Purchase Bundle",
  "充值后余额": "Balance after top-up",
  "请扫描用户二维码或输入用户账号绑定套餐": "Please scan user QR Code or registered bundle",
  "扫码绑定": "Scan to register",
  "手动输入用户帐号": "Manual input user ID",
  "将二维码/条码放入框内，即可自动扫描":
      "Insert QR or barcode into the frame to scan automatically",
  "二维码/条码": "QR code/Barcode",
  "输入用户账号": "Enter User ID",
  "取消": "Cancel",
  "所属地区": "Your area",
  "请选择所属地区": "Please select your area",
  "请选择换电套餐": "Please select Swapee bundle",
  "套餐绑定成功": "Bundle successfully registered",
  "租赁日期": "Date of Lease",
  "租赁网点": "Point of Lease",
  "解绑电池": "Deregister Battery",
  "待解绑电池": "Awaiting Battery Deregistration",
  "扫描电池SN码": "Scan Battery Serial No.",
  "请扫码录入/手动输入电池SN码": "Please scan to login/Manually Input Battery Serial No.",
  "确认解绑": "Confirm Deregistration",
  "电池解绑成功": "Battery Successfully Deregistered",
  "该用户暂无待解绑电池": "No battery awaiting deregistration",
  "搜索地点": "Search Location",
  "修改柜名": "Edit Kiosk Name",
  "请输入电柜名称，1~15个字符": "Please Enter Kiosk Name, 1-15 Characters",
  "修改地址": "Edit Address",
  "请输入机柜地址,1~30个字符": "Please Enter Kiosk Address, 1-30 Characters",
  "禁用电柜": "Disable Kiosk",
  "确认要禁用该电柜吗": "Confirm to disable kiosk?",
  "确认要启用该电柜吗": "Confirm to enable kiosk?",
  "修改图片": "Edit Photo",
  "请上传您的图片": "Please upload your photo",
  "还原": "Restore",
  "电柜管理": "Kiosk Management",
  "异常告警": "Abnormal alarm",
  "绑定套餐": "Register Bundle",
  "运营助手": "Operation Assistant",
  "电柜列表": "List of Kiosks",
  "在线状态": "Online Status",
  "在线": "Online",
  "设备ID": "Device ID",
  "电柜地址": "Kiosk Address",
  "输入电柜名/电柜ID/电柜地址搜索": "Enter Kiosk Name/Kiosk ID/Kiosk Address Search",
  "禁用": "Disable",
  "离线": "Offline",
  "电柜详情": "Kiosk Details",
  "仓位信息": "Kiosk Position Information",
  "电柜信息": "Kiosk Information",
  "更新时间": "Update time",
  "点击刷新": "Click to refresh",
  "点击以下仓位编号，可对相应的仓位进行管理操作，如需快捷操作，请点击":
      "Click the following kiosk position number to manage the corresponding kiosk. Please click for quick access",
  "一键开仓": "One-click kiosk door",
  "用户电池被吞并后系统自动锁定仓": "Withheld user battery, system auto-lock enabled",
  "仓门已打开": "Slot door is open",
  "锁定": "Lock",
  "已启用灭火器": "Fire extinguisher activated",
  "电量": "Power",
  "电池电压": "Battery Voltage",
  "仓内温度": "Slot Temperature",
  "充电电流": "Charging Current",
  "充电状态": "Charge Status",
  "编辑": "Edit : Edit",
  "重新定位": "Re-Positioning",
  "定位状态": "Positioning Status",
  "已定位": "Position Confirmed",
  "启用状态": "Activation Status",
  "主控板版本号": "Main control board version number",
  "机柜地址": "Kiosk Address",
  "实时性能": "Real-Time Performance",
  "机柜总电压": "Kiosk Overall Voltage",
  "机柜总电流": "Kiosk Overall Current",
  "柜体温度值": "Kiosk Temperature",
  "电表读数": "Meter Reading",
  "GSM信号强度": "GSM Signal Strength",
  "电池详情": "Battery Details",
  "所属代理商": "Affiliated agent",
  "实时状态": "Real-Time Status",
  "所在电柜": "Kiosk Location",
  "仓门编号": "Slot Door Number",
  "已循环次数/循环次数预警值": "Cycle times/cycle times warning value",
  "电池充电电流": "Battery Charging Current",
  "充电器电压": "Battery Charger Voltage",
  "充电器电流": "Battery Charger Current",
  "当前电量": "Current Electrical Power",
  "卡板温度值": "Card Controller Temperature",
  "电芯温度值": "Battery Cell Temperature",
  "环境温度值": "Ambient Temperature",
  "电池单芯电压值": "Battery Single Cell Voltage",
  "选择操作类型": "Select Operation Type",
  "仓位编号": "Slot Position Number",
  "禁用原因": "Reason for disabling",
  "开仓": "Open Slot",
  "仓位解禁": "Release Slot Position",
  "查看电池详情": "View battery details",
  "仓位禁用": "Disable Slot Position",
  "修改定位": "Edit Positioning",
  "机柜告警": "Kiosk Alarm",
  "机柜离线": "Kiosk Offline",
  "告警时间": "Alarm Time",
  "机柜名称": "Kiosk Name",
  "电池告警": "Battery Alarm",
  "烟雾告警": "Smoke Alarm",
  "历史搜索": "Search History",
  "搜索": "Search",
  "暂无相关告警记录": "No related alarm records yet",
  "总电压欠压": "Total undervoltage",
  "机柜上传": "Kiosk Upload",
  "电池上传": "Battery Upload",
  "MOS高温告警": "MOS High Temperature Alarm",
  "使用用户": "Account in use",
};
