part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();

  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTRY = _Paths.REGISTRY;
  static const MY = _Paths.MY;
  static const WALLET = _Paths.WALLET;
  static const SHOP = _Paths.SHOP;
  static const SETTING = _Paths.SETTING;
  static const MY_QRCODE = _Paths.MY_QRCODE;
  static const MORE = _Paths.MORE;
  static const ABOUT_US = _Paths.ABOUT_US;
  static const MY_PACKAGE = _Paths.MY_PACKAGE;
  static const CAMERA_SCAN = _Paths.CAMERA_SCAN;
  static const TRANSIT_INPUT = _Paths.TRANSIT_INPUT;
  static const EXCHANGE_INFO = _Paths.EXCHANGE_INFO;
  static const SERVING = _Paths.SERVING;
  static const PUT_MONEY = _Paths.PUT_MONEY;
  static const RECORDS = _Paths.RECORDS;
  static const VEHICLE = _Paths.VEHICLE;
  static const EXCHANGE_FINISH = _Paths.EXCHANGE_FINISH;
  static const NOTICE_LIST = _Paths.NOTICE_LIST;
  static const NOTICE_DETAIL = _Paths.NOTICE_DETAIL;
  static const CUSTOMER_SERVICE = _Paths.CUSTOMER_SERVICE;
  static const FEEDBACK = _Paths.FEEDBACK;
  static const URGE_CABINETS = _Paths.URGE_CABINETS;
  static const MULTILINGUAL = _Paths.MULTILINGUAL;
  static const EDIT_MOBILE = _Paths.EDIT_MOBILE;
  static const EDIT_NICKNAME = _Paths.EDIT_NICKNAME;
  static const PRODUCT_ADDRESS = _Paths.PRODUCT_ADDRESS;
  static const ORDER_DETAIL = _Paths.ORDER_DETAIL;
  static const ADMIN = _Paths.ADMIN;
  static const BIND_CONTACT = _Paths.BIND_CONTACT;
  static const BIND_CAR = _Paths.BIND_CAR;
  static const BIND_SUCCESS = _Paths.BIND_SUCCESS;
  static const SHOP_PRODUCT_DETAIL = _Paths.SHOP_PRODUCT_DETAIL;
  static const SUBMIT_ORDER = _Paths.SUBMIT_ORDER;
  static const PAY_ORDER = _Paths.PAY_ORDER;
  static const PAY_ORDER_SUCCESS = _Paths.PAY_ORDER_SUCCESS;
  static const USER_COMBO = _Paths.USER_COMBO;
  static const EDIT_ADDRESS = _Paths.EDIT_ADDRESS;
  static const ADD_ADDRESS = _Paths.ADD_ADDRESS;
  static const PAY_PACKAGE_LIST = _Paths.PAY_PACKAGE_LIST;
  static const PAY_COMBO = _Paths.PAY_COMBO;
  static const PAYMENT = _Paths.PAYMENT;
}

abstract class _Paths {
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const REGISTRY = '/registry';
  static const MY = '/my';
  static const WALLET = '/wallet';
  static const SHOP = '/shop';
  static const SETTING = '/setting';
  static const MY_QRCODE = '/my-qrcode';
  static const MORE = '/more';
  static const ABOUT_US = '/about-us';
  static const MY_PACKAGE = '/my-package';
  static const CAMERA_SCAN = '/camera-scan';
  static const TRANSIT_INPUT = '/transit-input';
  static const EXCHANGE_INFO = '/exchange-info';
  static const SERVING = '/serving';
  static const PUT_MONEY = '/put-money';
  static const RECORDS = '/records';
  static const VEHICLE = '/vehicle';
  static const EXCHANGE_FINISH = '/exchange-finish';
  static const NOTICE_LIST = '/notice-list';
  static const NOTICE_DETAIL = '/notice-detail';
  static const CUSTOMER_SERVICE = '/customer-service';
  static const FEEDBACK = '/feedback';
  static const URGE_CABINETS = '/urge-cabinets';
  static const MULTILINGUAL = '/multilingual';
  static const EDIT_MOBILE = '/edit-mobile';
  static const EDIT_NICKNAME = '/edit-nickname';
  static const PRODUCT_ADDRESS = '/product-address';
  static const ORDER_DETAIL = '/order-detail';
  static const ADMIN = '/admin';
  static const BIND_CONTACT = '/bind-contact';
  static const BIND_CAR = '/bind-car';
  static const BIND_SUCCESS = '/bind-success';
  static const SHOP_PRODUCT_DETAIL = '/shop-product-detail';
  static const SUBMIT_ORDER = '/submit-order';
  static const PAY_ORDER = '/pay-order';
  static const PAY_ORDER_SUCCESS = '/pay-order-success';
  static const USER_COMBO = '/user-combo';
  static const EDIT_ADDRESS = '/edit-address';
  static const ADD_ADDRESS = '/add-address';
  static const PAY_PACKAGE_LIST = '/pay-package-list';
  static const PAY_COMBO = '/pay-combo';
  static const PAYMENT = '/payment';
}
